services:
  - type: web
    name: atip-tracker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn atip_tracker.wsgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: PYTHON_VERSION
        value: 3.10.12
