# Generated by Django 5.1.3 on 2024-11-08 13:50

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ATIPRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("request_number", models.CharField(max_length=100, unique=True)),
                ("request_text", models.TextField()),
                ("institution", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted to Institution"),
                            ("RECEIVED", "Response Received"),
                            ("REJECTED", "Request Rejected"),
                            ("APPEALED", "Appealed to Access Commission"),
                            ("CLOSED_COMPLETE", "Closed - Fully Satisfied"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("date_submitted", models.DateField(default=django.utils.timezone.now)),
                ("response_due_date", models.DateField(blank=True, null=True)),
                ("appeal_deadline", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="atip_documents/")),
                ("description", models.CharField(blank=True, max_length=255)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="requests.atiprequest",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StatusTransition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "from_status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted to Institution"),
                            ("RECEIVED", "Response Received"),
                            ("REJECTED", "Request Rejected"),
                            ("APPEALED", "Appealed to Access Commission"),
                            ("CLOSED_COMPLETE", "Closed - Fully Satisfied"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "to_status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted to Institution"),
                            ("RECEIVED", "Response Received"),
                            ("REJECTED", "Request Rejected"),
                            ("APPEALED", "Appealed to Access Commission"),
                            ("CLOSED_COMPLETE", "Closed - Fully Satisfied"),
                        ],
                        max_length=20,
                    ),
                ),
                ("transition_date", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transitions",
                        to="requests.atiprequest",
                    ),
                ),
            ],
        ),
    ]
